// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("d742aa5f-0b4d-4ea6-96c4-3d15ca69f564"),
	English("6dc06590-1edf-41ca-b4dd-eee00242b66b"),
	French("13253ae4-5e81-4587-a3d6-83a3c6b972d0"),
	German("76073f05-de94-4f87-8619-801c0688305d"),
	Hindi("460e80da-f350-4986-a40a-3e5d98ec274c"),
	Portuguese("deb668b0-eed8-47b7-a040-0f0c692209a9"),
	Spanish("6bd9258d-c15a-4bd8-afdf-1fbd7a4e41f5"),
	Turkish("87adf45b-8cc2-4aac-8695-12317e980d82");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
