// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileactions.proxies;

public enum PictureQuality
{
	original("5a1f852a-f630-4ec4-994b-694b40b051bb"),
	low("f9325b3b-d898-4abd-8d9c-f22c9a6d5be0"),
	medium("29b0992e-801e-4831-b57e-df1b8a827b8d"),
	high("f4ada235-8c67-47c8-8608-a4f9e8fb29fc"),
	custom("f6a352cc-43f0-487b-866a-98ec2c0b76f8");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
