// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tasktracker.proxies;

/**
 * The priority options for a task
 */
public enum ENUM_Priority
{
	High("5cc9ce6d-04e0-48ff-af48-6b5f6bc5483f"),
	Medium("fb754530-de7d-47a6-b0bf-773a8124b6e5"),
	Low("84b1147e-edf9-4a4d-bd6a-f8bf45fe3f83");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Priority(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
