// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tasktracker.proxies;

/**
 * The status options for a task
 */
public enum ENUM_Status
{
	To_Do("2eea034c-fcca-48e5-8468-81ea578d4ca4"),
	Running("966e8294-3370-4cdc-9397-0f193418b89c"),
	Review("f99aaa17-19ef-4a98-b540-407333602143"),
	Done("6a3025e7-6f34-4fe1-94a9-271a44329110");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Status(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
