// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tasktracker.proxies;

public enum Enumeration
{
	SLA_Achieved("19a1911f-0b35-4fe8-b989-a5ed314b97b5"),
	SLA_Missed("3fbd944d-91f0-4c89-84e3-5eccafb705cf");

	private final java.lang.String i18nCaptionKey;
	
	private Enumeration(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
