// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendixsso.proxies;

public enum TokenType
{
	REFRESH_TOKEN("9de9a601-ef33-41a0-95d1-a5b5daff2667"),
	ID_TOKEN("09db0533-f00b-48ca-965f-4a6ea8f0ebf2"),
	ACCESS_TOKEN("43e7314d-3cd9-4dba-9327-1a295405c4d3");

	private final java.lang.String i18nCaptionKey;
	
	private TokenType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
